### PR TITLE
Added loopy the friendly pickle

### PR DESCRIPTION
**Pull request by ariporad**
Added loopy the friendly pickle at rloop.org/?loopy

Based off the query string (?loopy or ?loopy=true), a css class (.loopy) is added to the header, which changes the background image. The image is just the pickle with the background removed, pasted on the the normal background image.

The crazy filename is a big of security through obscurity. (I considered something really complex like having javascript inject a request to rloop.org/ga.js with the query string, and that would either return Google Analytics or GA + The Pickleifyr(tm), but decided against it).

### CODE REVIEW

**Comment by jdublu10** [comment]
Wait why exactly are we doing this?

**Comment by ariporad** [comment]
Fun.


Ari

**Comment by jdublu10** [comment]
Shouldn't we keep this project at least a teeny bit serious?

**Comment by ariporad** [comment]
I think it's keeping it a teeny bit serious to have a pickle at rloop.org?loopy. It's not there at rloop.org.

I really don't know how anyone would ever see it be accident, they'd either have to know, or look at the source.

Also, Check in #pr-media for a more detailed explanation.

**Comment by jdublu10** [comment]
Okay. Seems fun.

**Pull request merged**
